### ISSUE TITLE
Think about mapping to the permanent structure

### ISSUE THREAD

**Issue by slifty** [PermanentOrg/sftp-service#14]
Permanent is not a file system, but SFTP is ultimately a protocol for interacting with a filesystem.

This means there are a few concepts we're going to need to "map" between the two models.  In particular:

1) Permanent allows an account to have multiple archives.
2) Permanent allows for shared archives AND shared folders.
3) Is there an equivalent to a symlink in permanent?
4) What kind of things do we need to think about regarding STAT info (maybe nothing, but still)
5) What happens when there are file name collisions

There are likely other items as well.

These questions have good answers, but we should think through them and document those answers.  It's critical that a given file structure on a client machine map to a specific permanent data structure.

**Comment by kfogel** [comment]
Re name collisions: see the [design document](https://docs.google.com/document/d/13zsy2amn0AeEE_cA1gkZ9vM77acY3f3nxEkA7Rvox_g/edit#).

**Comment by slifty** [comment]
Two things:

## 1: Naming of archives

I'm currently thinking that archive folders on the user computer should have both the name AND the archive ID.

This does a few things:

1. It prevents the chance of archive naming collisions.
2. It gives us more explicit clarity about which archive a file belongs to during a sync (relying on JUST name without ID leaves more room for both system AND user error, which is a bigger deal when talking about the archive level since it is the file root).
3. It gives us the ability to support archive rename via rclone.

Another option would be to not show the archive name *AT ALL* -- just show the ID -- this has a benefit of creating any confusion related to archive renames.

I may do just the archive ID for the sake of the demo.

## 2: Archive as the only root level object type

I need to confirm with @cecilia-donnelly but right now I believe that archives are peerless -- that is, there are archives (owned, shared, doesn't matter), and they contain content, but there is no sibling object type to an archive.  Is there anything I'm missing?

If not, this would I that instead of:

```
- archives
| - Archive A
| | - ...
| - Archive B
| | - ...
| - Archive C
| | - ...
- ???
```

We could have

```
- Archive A
| - ...
- Archive B
| - ...
- Archive C
| - ...
```

### But maybe we want a README!
That said, I think there might be benefit from a situation where rclone results in:

```
- README.md
- archives
| - Archive A (1508123)
| | - ...
| - Archive B (1508124)
| | - ...
| - Archive C (1508125)
| | - ...
```

With the content of the readme being an explanation to the user of how to use rclone with permanent in future.

**Comment by kfogel** [comment]
In "this has a benefit of creating any confusion related to archive renames", did you mean "...avoiding any confusion..."?

If we're going to create a root folder, I would suggest calling it `Permanent.org Archives` or something else with the name "Permanent.org" in it (not just "Permanent" because, as we've noticed, that's a common word and could be misleading by itself).  I do like the idea of root-level folder, but with the README inside it.  Thus:

```
  - Permanent.org Archives
  | - README.txt
  | - Archive A (1508123)
  | | - ...
  | - Archive B (1508124)
  | | - ...
  | - Archive C (1508125)
  | | - ...
```
We would have to make decisions about top-level groupings now, right?  It's not easy to add them in the future, because `rclone` isn't client software that we have full control over; we'd have no easy way to "upgrade" the client-side layout from some old way we did things to some new way.

FWIW I think if we have archive names + IDs, then we don't need further groupings.  Users will generally know what archive they're addressing, and whether it's shared or not is not necessarily something they care about anyway when they're fetching or pushing content -- also, shared-vs-yours is something that can change without the archive's ID or even content changing.

**Comment by cecilia-donnelly** [comment]
Yes, archives are peerless.

I agree that archive ID is more important than name, but I would like to have both in the end.

**Comment by slifty** [comment]
> In "this has a benefit of creating any confusion related to archive renames", did you mean "...avoiding any confusion..."?

I guess if you're one of those people who sees confusion as a BAD THING then sure, fine, AVOIDING confusion. (to be more clear: yeah I meant avoiding whoops 😂)

> We would have to make decisions about top-level groupings now, right?

Yes, for some definition of "now" (not for Friday's demo, but very soon).

----

One thing to note about the root level folder: the user will be picking the root level folder by specifying what directory to clone into.  In that sense I think we may want to stay out of the the business of creating or naming the true *root* folder, and doing so might be confusing for future clone commands (as the user do I write `rclone permanet:/ ~/myPersonallyNamedRootFolder/` or do I `rclone permanet:/ ~/myPersonallyNamedRootFolder/Permanent.org\ Archives`)

Side note: I'd like to avoid having `.` or ` ` in any folders we name / create just because... blegh!

All that said, having individual archives as immediate children of whatever the clone root is sounds fine to me.

Just to tease out the alternative though: a benefit of having `archives` be a child of the root directory is that it provides future flexibility to add new categories of children down the line.  What if we DO decide to add a peer to archive somehow -- or we decide that applications shouldn't exist in the context of archives but instead should have their own folder (so `archives` and `applications` would become peers instead of having `app` inside of `archive`).

**Comment by kfogel** [comment]
Obviously no need to worry about it for Friday's demo, but can you put this as an agenda item for the next rclone group meeting?  I'd like to discuss it there, at least to the extent of establishing the process by which we (ultimately meaning Permanent) is going to make the decision.

**Comment by slifty** [comment]
We talked about this a bit in our rclone meeting today.  Decision is:

1) "archives" directory in the clone root.
2) "README" in the clone root as well explaining what's going on.

I believe the thinking is that in future we may have other root folders for one reason or another.

**Comment by slifty** [comment]
Robert mentioned that instead of archive ID in parens we should consider using the archive's "PA Number"

**Comment by kfogel** [comment]
> Robert mentioned that instead of archive ID in parens we should consider using the archive's "PA Number"

I believe that has solidified into a decision to definitely use the PA Number, right?

**Comment by slifty** [comment]
This has been thought about, and now I will close the issue (obviously any open tasks can be spun into new issues as needed)
