### ISSUE TITLE
Implement OPENDIR handler

### ISSUE THREAD

**Issue by slifty** [PermanentOrg/sftp-service#17]
The `OPENDIR` event is how an SFTP client signals to a server that they're about to ask some very serious and difficult questions about the contents of a given directory...

We just need to implement this in order to allow the client to scan a directory.  I think it would be good for this to be the event that triggers a Permanent API call to get the list of content in a given folder.  That list of content would then be *stored locally* by the SFTP service so future `READDIR` calls would allow for scanning of that content, as per the SFTP spec.

This issue will involve:

1. Implementing / using the getFolder method of the [Permanent SDK](https://github.com/PermanentOrg/permanent-sdk).
2. Deciding how (folder) data should be stored locally.
3. Deciding if there should be a timeout related to locally stored (folder) data.

~Note: It's very likely we'll want to just use redis for this data store.  It seems like an almost perfect solution at first glance.  That said, it's not a requirement and the decision is an exercise left to the assignee.~

## Resources

* [SFTP events (OPENDIR)](https://github.com/mscdex/ssh2/blob/master/SFTP.md)
* [Scanning Directories](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02#section-6.7)

**Comment by slifty** [comment]
Note: in our standup today the point was made that adding complexity (e.g. redis) should only happen if we truly feel we need it.  For instance if all we want is to store cached API results for open directories a well scoped variable cache could probably work just fine.

Worth thinking through a bit more, particularly thinking through scalability and what amount of data is likely to be needed the main potential benefits of redis that come to my mind immediately:

1. Automatic expiration / timeouts of data to prevent memory leaks
2. Allowing optimal resource allocation (e.g. the redis service could be deployed somewhere with more memory capacity but less network capacity).

There may be other tradeoffs as well.

**Comment by jasonaowen** [comment]
Thanks, @slifty!

From what I understand so far, it sounds like persisting this data is an optimization, right? I'm totally on board with adding Redis or whatever if and when we get to the point where there are costs to not having it - poor performance, OOM errors, scaling to multiple SFTP instances, and so on - but as a first pass, keeping data in memory seems simpler, clearer, and faster.

In particular, I think you already address point 1 with "well-scoped variable cache" - if the cache is attached to the connection, and the connection is properly torn down upon the client disconnecting, then I think the memory used for the cache should be freed and not leaked.

Point 2 sounds like a scalability thing, and we should consider it or something like it long-term - let's not paint ourselves into a corner where the in-memory cache will be exceedingly difficult to change out.

**Comment by slifty** [comment]
Agreed all around!  Implementing as an in-memory cache is a great way to go; down the line we can always make things more complex if optimization demands it OR if architecture changes demand it (e.g. if somehow we need shared memory across multiple instances of this service, which seems unlikely).

**Comment by slifty** [comment]
This is now complete as part of #34
