### ISSUE TITLE
Can we use the system sshd?

### ISSUE THREAD

**Issue by jasonaowen** [PermanentOrg/sftp-service#18]
The current plan is for the service to run its own SSH server, as provided by the [ssh2 package](https://www.npmjs.com/package/ssh2). This has a notable drawback: either the system sshd, or the service, will need to be run on a non-standard port, as both can't listen on the standard port for ssh. It also carries some risk, as ssh protocol bugs in the ssh2 package could cause our users' data to be exposed.

The system we will deploy this service on is going to have its own sshd running. Can we use that? It'd allow us to have a single open ssh port, running some of the most battle-hardened security code in the world, and staff would be able to log in to the system the same as any other system.

OpenSSH has a concept of [subsystems](https://man.openbsd.org/sshd_config#Subsystem), which are [simply normal programs run at login](https://superuser.com/a/425441). The program this repo provides would continue to talk the SFTP protocol, but would not run an SSH server to do so; instead, it would be invoked by the system sshd. This is the biggest unknown: can we extract the relevant functionality from the ssh2 package? It does not appear to be a use case upstream has considered. If not, is there an alternative package that we can use? Ideally, this would not imply a large change to this repo: we'll still be speaking SFTP, and we'll still need to handle all the same SFTP events.

We'd also have to figure out how to validate passwords, which would likely use the [keyboard-interactive method](https://man.openbsd.org/sshd_config#KbdInteractiveAuthentication) to use a custom [approval program](https://man.openbsd.org/login.conf.5#APPROVAL). At a glance, this has the advantage of appearing relatively straightfoward to implement, and easy to test; see also #15.

We would need to make sure that the system sshd configuration does not open us up to more risk than we save; we'd need to ensure that the system user we create cannot be accessed through eg `ssh sftp.permanent.org -l sftp /bin/sh`. I think/hope this mainly involves reading the OpenSSH documentation, and locking down the system user account.

This alternative architecture might make developing a bit more complicated; the current setup is very simple, and this proposal would require an sshd for full integration testing.

See also [the slack conversation](https://permanent-org.slack.com/archives/C01ARGVA849/p1644269841865019) that led to this issue.

**Comment by slifty** [comment]
I mentioned this in the thread but wanted to capture it here -- my initial thought based on my work with the ssh2 lib so far is that its SFTP implementation is deeply coupled with its SSH2 implementation.

We should dig in to confirm.

If that is the case, then integrating with OpenSSH would likely mean not using the ssh2 library and instead creating our own implementation of the SFTP protocol from "scratch" (what I mean here is the code that would read and write byte streams that adhere to the SFTP specification, and translate that into a node event API).  That implementation would be informed by the ssh2 package, but would be a separate code base that we maintain.

Not an impossible task by any means, but likely a multi-developer-month level project to bring to completion.

The good news is that we can continue with the ssh2 lib for the short term -- the SFTP events we need to handle and the resulting behavior will be the same regardless of what code base is triggering those events!

**Comment by jasonaowen** [comment]
> There's some security benefit to not using port 22 for SSH anyway, right?

I don't think it's a meaningful benefit; it's just obscurity. See also [this security.SE answer](https://security.stackexchange.com/a/32311).

**Comment by slifty** [comment]
We did resolve this in our infrastructure so I'm going to close the issue for now.
