### ISSUE TITLE
Node 16 EOL Sep 11, 2023

### ISSUE THREAD

**Issue by jasonaowen** [PermanentOrg/sftp-service#204]
This project is currently using Node.js 16:

https://github.com/PermanentOrg/sftp-service/blob/4825fb281c599c59e03ac603df39fdac6d251934/.node-version#L1

Node.js is currently in maintenance LTS, and [maintenance expires September 11, 2023](https://nodejs.org/en/blog/announcements/nodejs16-eol).

Before support runs out, we should upgrade at least to 18 (supported through April 2025), and ideally to 20 (supported through April 2026).

**Comment by slifty** [comment]
re 18 vs 20 I think it's permanent policy to be on the `active` version so I'll move to 18 for now and in October someone should update to 20
