### ISSUE TITLE
Design and execute deployment plan

### ISSUE THREAD

**Issue by slifty** [PermanentOrg/sftp-service#39]
How should this be served?  How should it be deployed?  Many questions, we need answers.

**Comment by cecilia-donnelly** [comment]
https://pad.opentechstrategies.com/p/2022-09-20-sftp-deploy

**Comment by slifty** [comment]
We're now deploying SFTP service!  It's on production, staging, dev, and there are CI pipelines that build the service and push it out similar to other permanent projects.
