### ISSUE TITLE
'rclone copy' doesn't download all of my files

### ISSUE THREAD

**Issue by kfogel** [PermanentOrg/sftp-service#54]
I just did `rclone copy permanent-prod:/ ./permanent-down`, but I didn't get all of the files from my (one) archive.  I'll show a full transcript of the session later, but first here's the TL;DR:

I *should* have gotten the following file tree (folders are indicated with a trailing "/" -- the "/" is not actually in the name, of course):

```
archives/
  kfogel OTS test (13539)/
    My Files/
      dennys-fake-maple-syrup-2022-05-11.jpg  
      Screenshot from 2022-07-12 14-17-51.png   
      tex-kerning.png   
      worker-digging.png
      Cables I have known/
        50-foot-VGA-cable.jpg
      GNOME Workspace Switcher bug/  
        gnome-3-shell-42.0-workspace-switcher-bottom-indicator-ws1-to-ws2-2022-04-10.png  
        gnome-3-shell-42.0-workspace-switcher-bottom-indicator-ws2-to-ws1-2022-04-10.png
        This subfolder is just to, you know, test subfolders./
          uncle-neatest-whiskey-weird-endorsement.jpg
        This is an empty subfolder./
```

But instead I got this file tree:

```
archives/
  kfogel OTS test (13539)/
    My Files/
      dennys-fake-maple-syrup-2022-05-11.jpg  
      Screenshot from 2022-07-12 14-17-51.png   
      tex-kerning.png   
      worker-digging.png
      Cables I have known/
        50-foot-VGA-cable.jpg
      GNOME Workspace Switcher bug/  
        gnome-3-shell-42.0-workspace-switcher-bottom-indicator-ws1-to-ws2-2022-04-10.png  
        gnome-3-shell-42.0-workspace-switcher-bottom-indicator-ws2-to-ws1-2022-04-10.png
```

Notice how the two subfolders of the `GNOME Workspace Switcher bug/` folder are missing, and thus the JPG image file in one of those subfolders is also missing.

(By the way, not that it matters for this bug report, but yes, the name of that missing JPG image has a typo.  In my actual archive I've changed the "name" of that record, but of course that doesn't affect the downloadName, which still has the original name.  Later I may just delete the file and re-upload it with a fixed name, but I didn't want to introduce that variable while reporting this issue.)

So:

Are the subfolders missing maybe because their names end with dot?

Here's a transcript of my complete session -- notice the interesting-and-possibly-relevant error messages:

```
$ cat ~/.config/rclone/rclone.conf 
[permanent-prod]
type = sftp
host = sftp.permanent.org
user = kfogel@opentechstrategies.com
ask_password = true

$ time rclone copy permanent-prod:/ ./permanent-down
Enter SFTP password: *************************************

<3>ERROR : archives/kfogel OTS test (13539)/My Files/GNOME Workspace Switcher bug/This subfolder is just to, you know, test subfolders.: error reading source directory: List failed: is a file not a directory
<3>ERROR : archives/kfogel OTS test (13539)/My Files/GNOME Workspace Switcher bug/This is an empty subfolder.: error reading source directory: List failed: is a file not a directory
<3>ERROR : Attempt 1/3 failed with 3 errors and: march failed with 2 error(s): first error: List failed: is a file not a directory
<3>ERROR : archives/kfogel OTS test (13539)/My Files/GNOME Workspace Switcher bug/This subfolder is just to, you know, test subfolders.: error reading source directory: List failed: is a file not a directory
<3>ERROR : archives/kfogel OTS test (13539)/My Files/GNOME Workspace Switcher bug/This is an empty subfolder.: error reading source directory: List failed: is a file not a directory
<3>ERROR : Attempt 2/3 failed with 3 errors and: march failed with 2 error(s): first error: List failed: is a file not a directory
<3>ERROR : archives/kfogel OTS test (13539)/My Files/GNOME Workspace Switcher bug/This subfolder is just to, you know, test subfolders.: error reading source directory: List failed: is a file not a directory
<3>ERROR : archives/kfogel OTS test (13539)/My Files/GNOME Workspace Switcher bug/This is an empty subfolder.: error reading source directory: List failed: is a file not a directory
<3>ERROR : Attempt 3/3 failed with 3 errors and: march failed with 2 error(s): first error: List failed: is a file not a directory

### It just hung here for many minutes; eventually I did ^C to interrupt and exit.
### That's probably known bug https://github.com/PermanentOrg/sftp-service/issues/45.

real	11m2.034s
user	0m0.533s
sys	0m0.539s
$ 
```

If anyone wants the password to my account in order to reproduce this, just let me know; there's nothing private in there.

For your amusement, I will attach the missing JPG image file here (using the new user-visible name that it now shows in the Permanent web UI).  I think you'll agree that there is indeed a very odd claim being made on the front of that bottle.

![weird-whiskey-endorsement](https://user-images.githubusercontent.com/401111/214960557-f6612439-d501-4c47-b503-4ba734eaf7b0.jpg)

**Comment by Fenn-CS** [comment]
> (By the way, not that it matters for this bug report, but yes, the name of that missing JPG image has a typo. In my actual archive I've changed the "name" of that record, but of course that doesn't affect the downloadName, which still has the original name. Later I may just delete the file and re-upload it with a fixed name, but I didn't want to introduce that variable while reporting this issue.)


Changing the name of a record, should affect its `downloadName`

**Comment by kfogel** [comment]
@Fenn-CS Well, when I changed the name of that record today, its `downloadName` was not affected.  I changed the name (in the Permanent UI) to "weird-whiskey-endorsement".  Then, *after* doing that, I downloaded the file, using the download button at the top right (the down-arrow-inside-a-cloud next to the word "Download"), and the name of the file that got downloaded was exactly the same as what I originally uploaded: "uncle-neatest-whiskey-weird-endorsement.jpg".

Does that mean there's a separate other bug here as well?

**Comment by slifty** [comment]
Ha so this bug is actually already linked to a TODO and I'm glad you caught it because, as is the nature of TODOs without issues... I totally forgot!

See: https://github.com/PermanentOrg/sftp-service/blob/main/src/utils/getFileType.ts

```
  // TODO: this is not a real rule.
  // We are going to need to ultimately track what paths are files / folders
  // based on the information we get from the permanent backend (or the client)
```

This will be good to fix up before the demo!

**Comment by Fenn-CS** [comment]
@kfogel I don't think so. The download button in Permanent probably does not use download names.

The only way to know if the download name actually changed is to check in the dB or by you performing another down-sync after changing the download name.
l

**Comment by kfogel** [comment]
@Fenn-CS Pardon me, but if the *dowload button* does not use `downloadName`, why do we call the field `downloadName`?

Also, if the Permanent web client wasn't getting that original filename from `downloadName`, where else could it have gotten the name from?

**Comment by kfogel** [comment]
@slifty writes:
> This will be good to fix up before the demo!

E-yup :-).  I will continue to QA in as arbitrary a way as I can.  Have you got a ticket for the "." bug yet?  (I'll subscribe if so.)

**Comment by slifty** [comment]
@kfogel this is the ticket for that bug (you are subscribed!)

**Comment by cecilia-donnelly** [comment]
@kfogel We created the `downloadName` field for this SFTP work and you may recall that it went through a few name changes along the way! `downloadName` seemed to make the most sense. We have a few places where we name the file, some of which are considered metadata. The one you see in the Permanent interface is the `displayName`. I believe the download button usually returns a file given its `uploadFileName`.
