### ISSUE TITLE
Cache per user rather than per connection

### ISSUE THREAD

**Issue by slifty** [PermanentOrg/sftp-service#76]
The sftp service cache was written in in a way that assumed exactly one active sftp connection per rclone "session", which is an invalid assumption and can lead to correctness issues when there is uploading happening.

**Short summary:** When there are multiple simultaneous connections (e.g., the user just runs two rclones at the same time against the same archive, or maybe rclone itself decides to use multiple simultaneous connections as some kind of network optimization), and files/folders in Permanent are being written to, then the cached versions of those files / folders on other connections will not be updated and hilarity will ensue.  (In addition to the correctness issue, this is also an efficiency loss -- N-1 connections in the same session don't get to take advantage of the caching already done by any given connection in that session.)

**Longer explanation:** Permanent has no API that converts a path to an item ID.  If the SFTP Service is asked to open a certain path, then it has to walk back up the path and build the virtual filesystem from the top down, and only then can it know what item ID to open -- and each component along that path is an API call.  Therefore, as an optimization, we cache those responses as we go, so that we don't have to make those API calls every time: we're usually walking paths we've walked before, so let's use the answer we remembered last time.  Well, that's great for reading, but we have a cache invalidation problem if we're writing.  And we do invalidate the cache!  But we can only do so in the connection that's doing the write -- current implementation has one cache per connection.  What if the user is running multiple SFTP connections?  Or what if rclone itself decides to spin up multiple connections, the way web browsers do?

**Solution:** I believe this can be resolved by having a cache manager that provides a single cache for each authenticated user rather than on a per-connection basis.  This needs to be done thoughtfully in order to avoid risks of caches lasting longer than they ought to, or having data leak between users.  Remember that it's okay for a cache to be cleaned up too soon -- all that means is that we get a bit less efficient, because we have to make some API calls that could have been avoided if the cache were available.  On the other hand, it's *not* okay to fail to clean up caches, even occasionally: that would cause a slow-but-unbounded memory leak.

(Editorial note: This initial description was expanded by Karl, with Dan's permission, after our 2023-02-23 regular dev meeting.)

**Comment by kfogel** [comment]
Is this a possible correctness issue?

Also, what happens in the case of totally separate simultaneous connections?  E.g.:

1. I start an rclone SFTP session uploading data to my Archive A.  (I have verbose logging on, so I can see per-file progress.)
2. I see File F fly by -- as far as I know, it has now been uploaded.
3. While the original session is still going on, I open another separate rclone session, downloading data from Archive A.
4. Will my second rclone session receive File F?

I think this is theoretically different from the scenario you're worried about (your scenario involves different connections within the same session, IIUC), but in a sense maybe it's essentially the same race condition?

**Comment by slifty** [comment]
The concept of a session here only exists from the perspective of rclone -- which is to say I believe from our perspective the situation you're describing is the same thing.
