### ISSUE TITLE
Return a more specific error code for archive records without populated files

### ISSUE THREAD

**Issue by slifty** [PermanentOrg/sftp-service#97]
When a new file is created it can take a little while for permanent to fully process the file.

While processing is still happening the archive record is still a valid object, but its original file has no size or downloadUrl.  It could take an arbitrary amount of time for these files to resolve.  During that time, the files are unreadable.  `READ` attempts will fail, and STAT data (e.g. size) will be incorrect.

I think the "real filesystem" equivalent of this situation might be that the file is unreadable (even if only temporarily).  Our service should simulate that behavior and return the proper error codes so it isn't interpreted as a "failure".  We also should not be giving a `WARN` in our logs in this circumstance, as it is known and expected behavior.

I believe this change will also address some of the issues raised in #94

**Comment by slifty** [comment]
I think the best bet may be:

```

   SSH_FX_LOCK_CONFLICT
      The file could not be opened because it is locked by another
      process.
```

One reason I like this is it also signals that the state is temporary; that might result in rclone attempting again after some degree of timeout.

**Comment by slifty** [comment]
The ssh2 upstream is explicitly only implementing v3 of the SFTP specification (which is the version that is supported by OpenSSH).  I'm going to close this issue since I believe we're doing the best we can given that (understandable) constraint.

https://github.com/mscdex/ssh2/issues/1278#issuecomment-1456842948

**Comment by kfogel** [comment]
Expanding what @slifty is saying above:

Despite deciding that `SSH_FX_LOCK_CONFLICT` would be the right error to send back, we can't actually do that because the versions >3 of SFTP that we'd need to use are not actually supported by the SSH implementations that in practice everyone is running SFTP over.

So instead we're sending back a generic FAIL error, i.e., what we're already doing.
